(()=>{'use strict';if(!('serviceWorker' in navigator))return;
let registration,requested=false,reloading=false,checking=false,pageStale=false;
const box=document.createElement('div');box.id='baristaUpdateTools';box.style.cssText='display:flex;align-items:center;gap:8px;font:14px system-ui';
const button=document.createElement('button'),dot=document.createElement('span'),note=document.createElement('span');button.type='button';button.setAttribute('aria-label','Refresh and update app');button.title='Refresh and update app';button.style.cssText='position:relative;min-width:46px;min-height:46px;padding:10px;border-radius:12px;border:1px solid #cdbdab;background:white;color:#503827';button.innerHTML='<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/></svg>';dot.style.cssText='position:absolute;top:-3px;right:-3px;width:11px;height:11px;border-radius:50%;background:#d62f2f;border:2px solid white';dot.hidden=true;button.append(dot);box.append(button,note);const actions=document.querySelector('.barista-actions');if(actions)actions.append(box);else{box.style.cssText+=';position:fixed;bottom:12px;left:12px;z-index:9998;background:white;padding:8px;border-radius:12px';document.body.append(box);}
function blocked(){if(['kbr_menu_write_v1'].some(k=>localStorage.getItem(k))){note.textContent='Finish syncing saved changes first.';return true;}if(typeof cart!=='undefined'&&cart.length){note.textContent='Send or clear the cart before updating.';return true;}if(document.querySelector('dialog[open],#cloudScreen')){note.textContent='Finish the current edit first.';return true;}return false;}
function apply(){if(!requested||!registration?.waiting)return;if(blocked()){requested=false;return;}reloading=true;registration.waiting.postMessage({type:'SKIP_WAITING'});note.textContent='Updating…';}
function waiting(){dot.hidden=!(registration?.waiting||pageStale);button.title=(registration?.waiting||pageStale)?'Update available — press to install':'Refresh and update app';button.setAttribute('aria-label',button.title);apply();}
async function check(){if(checking||!registration)return;checking=true;try{await registration.update();waiting();if(requested&&!registration.waiting&&!registration.installing){requested=false;location.reload();}}catch(e){requested=false;note.textContent='Connect to the internet to update.';}finally{checking=false;}}
button.onclick=()=>{if(!registration){note.textContent='Update check is starting…';return;}if(blocked())return;requested=true;note.textContent='Checking…';if(registration.waiting)apply();else check();};
navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading){reloading=false;location.reload();}else{pageStale=true;dot.hidden=false;note.textContent='Refresh to load the updated app.';}});
navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>{registration=r;waiting();r.addEventListener('updatefound',()=>{const worker=r.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed')waiting();if(worker.state==='redundant'){requested=false;note.textContent='Update did not finish. Try again.';}});});check();}).catch(()=>note.textContent='Update checks unavailable.');setInterval(()=>{if(!document.hidden)check();},60000);window.addEventListener('focus',check);window.addEventListener('online',check);
})();
