'use strict';
(()=>{
 const cloud=KBRCloud,ui=KBRSyncUI,key='kbr_menu_write_v1';let role='',revision=0,ready=false,busy=false,polling=false;
 function apply(row){ui.applyMenu(row);revision=row.revision;menu=MenuStore.load();render();}
 async function submit(operation){const row=await cloud.rpc('kbr_save_menu',operation.args);if(row.conflict){localStorage.setItem('kbr_last_menu_conflict',JSON.stringify(operation));localStorage.removeItem(key);const rows=await cloud.request('/rest/v1/kbr_menu?id=eq.1&select=*');apply(rows[0]);ui.close();throw new Error('Another device edited the menu. The shared menu was reloaded; please make your edit again.');}apply(row);localStorage.removeItem(key);ui.close();cloud.status('Connected · shared menu saved');return menu;}
 async function retry(){if(busy)return;const op=cloud.read(key);if(!op)return;busy=true;ui.screen('Saving shared menu…','Retrying the same menu change.');try{await submit(op);$('editor').close();status('Shared menu saved on all devices.');}catch(e){if(cloud.read(key))showError(e);else{ui.close();status(e.message);}}finally{busy=false;}}
 function showError(error){cloud.status('Menu change waiting to sync',true);ui.screen('Menu change waiting to sync',error.message,[['Retry saved change',retry],['Sign in again',()=>location.href='sync-login.html?next=menu.html']]);}
 MenuStore.save=async items=>{if(!ready||busy)throw new Error('Wait for the shared menu to connect.');if(role!=='owner')throw new Error('Owner login is required to change the menu.');if(cloud.read(key)){showError(new Error('Finish the saved change first.'));throw new Error('A menu change is already waiting to sync.');}const valid=MenuStore.validate(items),op={args:{p_items:valid,p_expected_revision:revision,p_operation:cloud.uuid()}};localStorage.setItem(key,JSON.stringify(op));busy=true;ui.screen('Saving shared menu…','Prices and availability will update on both devices after confirmation.');try{return await submit(op);}catch(e){if(cloud.read(key))showError(e);throw e;}finally{busy=false;}};
 async function poll(){if(!ready||busy||polling||cloud.read(key)||document.hidden)return;polling=true;try{const rows=await cloud.request('/rest/v1/kbr_menu?id=eq.1&select=id,revision');if(rows[0]&&rows[0].revision!==revision){if($('editor').open){status('Another device changed the menu. Finish or cancel this edit; saving will check for a conflict.');}else{const latest=await cloud.request('/rest/v1/kbr_menu?id=eq.1&select=*');apply(latest[0]);}}cloud.status('Connected · updates every 3 sec');}catch(e){cloud.status('Disconnected · saved menu visible',true);}finally{polling=false;}}
 async function start(){if(!cloud.requireLogin())return;ui.screen('Connecting menu…','Loading the shared prices and availability.');try{ui.rememberBackup();role=await cloud.role();if(role!=='owner')throw new Error('Owner login required for Manager.');apply(await ui.menuReady(role));ready=true;ui.close();cloud.status('Connected · shared menu');if(cloud.read(key))showError(new Error('A previous menu change needs confirmation.'));if(role!=='owner'){document.querySelectorAll('main button,main input,main select').forEach(el=>el.disabled=true);status('This account can view the menu. An owner login is needed to edit it.');}}catch(e){ui.screen('Could not connect',e.message,[['Retry connection',start],['Sign in again',()=>location.href='sync-login.html?next=menu.html']]);}}
 window.addEventListener('online',()=>cloud.read(key)?retry():poll());window.addEventListener('focus',poll);setInterval(poll,cloud.config.pollMs);start();
})();
