'use strict';
const $=id=>document.getElementById(id);
let menu=MenuStore.load(), editing=-1, photoBusy=false;
function status(message){$('status').textContent=message;$('status').style.display='block';}
function availabilityLabel(value){return value==='out-of-stock'?'Out of Stock':value==='not-available'?'Not Available':'Available';}
async function changeAvailability(i,value){try{const next=menu.map((p,k)=>k===i?{...p,availability:value}:p);menu=await MenuStore.save(next);render();status(menu[i].name+': '+availabilityLabel(value));}catch(e){render();status('Could not save: '+e.message);}}
function render(){
 $('list').replaceChildren();$('categories').replaceChildren();
 [...new Set(menu.map(p=>p.category))].forEach(c=>{const o=document.createElement('option');o.value=c;$('categories').append(o);});
 const query=$('search').value.toLowerCase();
 menu.forEach((p,i)=>{if(!(p.name+' '+p.category).toLowerCase().includes(query))return;
 const card=document.createElement('article'),info=document.createElement('div'),title=document.createElement('h3'),meta=document.createElement('small'),prices=document.createElement('p'),edit=document.createElement('button');
 title.textContent=p.name;meta.textContent=p.category+' · '+availabilityLabel(p.availability);prices.textContent=p.pricePending?'Price not set — edit to enable ordering':p.sizes.map((s,k)=>s+' · ₱'+p.prices[k]).join(' / ')+(p.premium?' | Premium: '+p.premiumSizes.map((s,k)=>s+' · ₱'+p.premium[k]).join(' / '):'');edit.textContent='✎ Edit';edit.onclick=()=>open(i);info.append(title,meta,prices);const actions=document.createElement('div'),availability=document.createElement('select');availability.setAttribute('aria-label','Availability for '+p.name);[['available','Available'],['not-available','Not Available'],['out-of-stock','Out of Stock']].forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;availability.append(option);});availability.value=p.availability||'available';availability.onchange=()=>changeAvailability(i,availability.value);const remove=document.createElement('button');remove.textContent='Remove menu item';remove.style.color='#a12424';remove.onclick=async()=>{if(!confirm('Remove '+p.name+' from the ordering menu? Existing orders and transactions keep their recorded item.'))return;try{menu=await MenuStore.save(menu.filter((_,k)=>k!==i));render();status('Menu item removed.');}catch(e){status('Could not remove: '+e.message);}};actions.append(availability,edit,remove);card.append(info,actions);$('list').append(card);
 });
 if(!$('list').children.length)$('list').textContent='No matching menu items.';
}
function row(target,size='',price=''){
 const el=document.createElement('div');el.className='row';const s=document.createElement('input'),p=document.createElement('input'),b=document.createElement('button');s.placeholder='Size / portion';s.value=size;s.required=true;s.setAttribute('aria-label','Size or portion');p.type='number';p.min='0';p.max='1000000';p.step='0.01';p.required=true;p.placeholder='Price ₱';p.value=price;p.setAttribute('aria-label','Price in pesos');b.type='button';b.textContent='×';b.setAttribute('aria-label','Remove size');b.onclick=()=>el.remove();el.append(s,p,b);$(target).append(el);
}
function togglePremium(){$('premiumPanel').hidden=!$('premiumEnabled').checked;$('premium').querySelectorAll('input').forEach(e=>e.disabled=!$('premiumEnabled').checked);}
function open(i){editing=i;const p=i<0?{name:'',category:'',sizes:['12 oz','16 oz','22 oz'],prices:['','',''],image:'',food:false}:menu[i];$('form').reset();$('error').textContent='';$('title').textContent=i<0?'Add menu item':'Edit '+p.name;$('name').value=p.name;$('category').value=p.category;$('food').checked=!!p.food;$('availability').value=p.availability||'available';$('image').value=p.image||'';$('standard').replaceChildren();$('premium').replaceChildren();p.sizes.forEach((s,k)=>row('standard',s,p.pricePending?'':p.prices[k]));(p.premiumSizes||['16 oz','22 oz']).forEach((s,k)=>row('premium',s,p.premium?.[k]??''));$('premiumEnabled').checked=!!p.premium;togglePremium();preview();$('editor').showModal();}
function preview(){const src=$('image').value;const safe=/^(images\/|https?:\/\/|data:image\/(png|jpeg|webp);base64,)/i.test(src);$('preview').hidden=!safe;if(safe)$('preview').src=src.startsWith('images/')?new URL(src,KBR_APP_LINKS.orderingUrl).href:src;else $('preview').removeAttribute('src');}
function variants(id){const rows=[...$(id).children];return {sizes:rows.map(r=>r.children[0].value.trim()),prices:rows.map(r=>r.children[1].value===''?NaN:Number(r.children[1].value))};}
$('form').onsubmit=async e=>{e.preventDefault();if(photoBusy){$('error').textContent='Wait for the photo to finish.';return;}try{const v=variants('standard'),premium=$('premiumEnabled').checked?variants('premium'):null;const p={name:$('name').value,category:$('category').value,food:$('food').checked,availability:$('availability').value,image:$('image').value.trim(),...v,premium:premium?.prices||null,premiumSizes:premium?.sizes||null};const next=menu.slice();if(editing<0)next.push(p);else next[editing]=p;menu=await MenuStore.save(next);$('editor').close();render();status('Menu saved. Prices and availability updated.');}catch(err){$('error').textContent='Could not save: '+err.message;}};
$('photo').onchange=async()=>{const file=$('photo').files[0];if(!file)return;photoBusy=true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Choose PNG, JPG, or WebP.');if(file.size>10*1024*1024)throw new Error('Choose a photo smaller than 10 MB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,640/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();$('image').value=canvas.toDataURL('image/jpeg',0.8);preview();$('error').textContent='';}catch(e){$('error').textContent=e.message;}finally{photoBusy=false;}};
$('add').onclick=()=>open(-1);$('cancel').onclick=()=>$('editor').close();$('search').oninput=render;$('image').oninput=preview;$('premiumEnabled').onchange=togglePremium;$('addSize').onclick=()=>row('standard');$('addPremium').onclick=()=>row('premium');
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(menu,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='kbr-menu-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>5*1024*1024)throw new Error('Backup is too large.');const next=MenuStore.validate(JSON.parse(await file.text()));if(!confirm('Replace the current menu with '+next.length+' imported items? Existing orders will stay unchanged.'))return;menu=await MenuStore.save(next);render();status('Menu imported successfully.');}catch(e){status('Could not import: '+e.message);}finally{$('import').value='';}};
window.addEventListener('storage',e=>{if(e.key===MenuStore.key){menu=MenuStore.load();render();if($('editor').open)$('editor').close();status('Menu updated in another tab.');}});render();
