(()=>{'use strict';const $=id=>document.getElementById(id),data=KBRSales;let records=[],rawRows=[],stats,limit=100;const money=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(n);
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function preset(){const end=data.day(new Date());let start=end;if($('period').value==='all')start=records.map(r=>r.day).filter(Boolean).sort()[0]||end;else if(['7','30'].includes($('period').value)){const d=new Date(end+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-Number($('period').value)+1);start=d.toISOString().slice(0,10);}else if($('period').value==='custom')return;$('from').value=start;$('to').value=end;}
function table(title,values,label,chronological=false){const rows=Object.entries(values).sort(chronological?(a,b)=>a[0].localeCompare(b[0]):(a,b)=>b[1]-a[1]);const max=Math.max(1,...rows.map(x=>x[1]));return `<section><h2>${title}</h2><table><thead><tr><th>${label}</th><th>Quantity</th></tr></thead><tbody>${rows.map(([k,v])=>`<tr><td>${escape(k)}<div class="bar"><span style="width:${v/max*100}%"></span></div></td><td>${v}</td></tr>`).join('')||'<tr><td colspan="2">No sales in this period.</td></tr>'}</tbody></table></section>`;}
function render(){const from=$('from').value,to=$('to').value;if(!from||!to||from>to){$('status').textContent='Choose a valid date range.';return;}stats=data.aggregate(records,from,to);limit=100;
$('cards').innerHTML=[['Completed transactions',stats.selected.length],['Sales',money(stats.sales)],['Drink cups sold',stats.drinks],['All drink cups used',stats.consumptionDrinks],['Barista Drinks',stats.freeDrinks],['Charged to Kuya John',money(stats.ownerChargeValue)],['Food quantity',stats.food],['Average drink cups / day',(stats.drinks/stats.days).toFixed(1)]].map(([label,value])=>`<div class="card">${label}<b>${value}</b></div>`).join('');
$('charts').innerHTML=table('Most bought drinks',stats.byDrink,'Drink')+table('Drink sizes',stats.bySize,'Size')+table('Categories',stats.byCategory,'Category')+table('Orders by date',stats.byDay,'Date',true)+table('Orders by hour',stats.byHour,'Hour · Philippine time',true)+table('Service types',stats.byService,'Service');
forecast();transactions();}
function forecast(){let stock={};try{stock=JSON.parse(localStorage.getItem('kbr_cup_stock_estimate_v1')||'{}');}catch{}const sizes=['12 oz','16 oz','22 oz'];for(const size of Object.keys(stats.consumptionBySize))if(!sizes.includes(size)&&/oz/i.test(size))sizes.push(size);
$('forecast').innerHTML='<table><thead><tr><th>Size</th><th>Cups in stock</th><th>Average / day</th><th>Estimated days left</th></tr></thead><tbody>'+sizes.map(size=>{const rate=(stats.consumptionBySize[size]||0)/stats.days;const value=stock[size];return `<tr><td>${escape(size)}</td><td><input aria-label="${escape(size)} cups in stock" data-size="${escape(size)}" type="number" min="0" step="1" value="${Number.isFinite(Number(value))&&value!==undefined?Number(value):''}"></td><td>${rate.toFixed(2)}</td><td>${value===undefined?'Enter stock':rate>0?(Number(value)/rate).toFixed(1):'No recorded demand'}</td></tr>`;}).join('')+'</tbody></table>';
$('forecast').querySelectorAll('input').forEach(input=>input.onchange=()=>{const value=Number(input.value);if(input.value===''||!Number.isFinite(value)||value<0)delete stock[input.dataset.size];else stock[input.dataset.size]=value;try{localStorage.setItem('kbr_cup_stock_estimate_v1',JSON.stringify(stock));forecast();}catch{$('status').textContent='Could not save stock counts on this device.';}});}
function transactions(){const rows=[...stats.selected].sort((a,b)=>(b.orderedAt||b.day).localeCompare(a.orderedAt||a.day));$('transactionsHint').textContent=`Showing ${Math.min(limit,rows.length)} of ${rows.length} transactions.`;$('transactions').innerHTML='<table><thead><tr><th>Order</th><th>Ordered on</th><th>Items</th><th>Payment / charged to</th><th>Sales</th><th>Free / owner-charge value</th></tr></thead><tbody>'+rows.slice(0,limit).map(r=>`<tr><td>${escape(r.no)}</td><td>${escape(r.day)} ${escape(r.orderedAt?new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',hour:'numeric',minute:'2-digit'}).format(new Date(r.orderedAt)):r.time)}</td><td>${(r.items||[]).map(x=>escape(`${x.qty} × ${x.name} ${x.size||''}`)).join('<br>')}</td><td>${escape(KBRPayments.label(r))}</td><td>${money(KBRPayments.sales(r))}</td><td>${KBRPayments.isNonSale(r)?money(KBRPayments.value(r)):'—'}</td></tr>`).join('')+'</tbody></table>';$('more').hidden=limit>=rows.length;}
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function csvCell(value){let s=String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('csv').onclick=()=>{if(!stats)return;const lines=[['Order','Ordered date','Ordered time','Category','Drink / food','Type','Size','Sweetness','Service','Payment','Quantity','Unit price','Item value','Sales line total','Sales transaction total','Payment details','Non-sale transaction value']];for(const r of stats.selected)for(const x of r.items||[])lines.push([r.no,r.day,r.time,x.category,x.name,x.type,x.size,x.sweetness,x.serviceType||r.serviceType,r.payment,x.qty,x.price,(Number(x.qty)||0)*(Number(x.price)||0),KBRPayments.isNonSale(r)?0:(Number(x.qty)||0)*(Number(x.price)||0),KBRPayments.sales(r),KBRPayments.label(r),KBRPayments.isNonSale(r)?KBRPayments.value(r):0]);download('\ufeff'+lines.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8',`KBR-sales-${$('from').value}-${$('to').value}.csv`);};
$('backup').onclick=()=>{if(!records.length){$('status').textContent='Load sales before downloading a backup.';return;}download(JSON.stringify({format:'kbr-sales-backup-v1',exportedAt:new Date().toISOString(),orders:rawRows,receipts:records},null,2),'application/json',`KBR-all-sales-${data.day(new Date())}.json`);};
async function load(){if(!KBRCloud.requireLogin())return;$('load').disabled=true;$('status').textContent='Loading all completed transactions…';try{if(await KBRCloud.role()!=='owner')throw new Error('Owner login is required for sales analysis.');document.getElementById('salesContent').hidden=false;const rows=await KBRCloud.rows('/rest/v1/kbr_orders?status=eq.completed&select=id,order_number,receipt,created_at,updated_at&order=order_number.desc');rawRows=rows;records=rows.filter(r=>r.receipt).map(data.normalize);
const backup=KBRCloud.read('kbr_before_cloud_v1',{});const seen=new Set(records.map(r=>String(r.no)));for(const old of backup.history||[]){if(!old._cloudId&&!seen.has(String(old.no))){records.push(data.normalize(old));seen.add(String(old.no));}}
preset();render();const unknown=records.filter(r=>!r.day).length;$('status').textContent=`Loaded ${records.length} completed transactions. ${unknown?unknown+' older receipts have no usable date and are included only in the backup.':''}`;
}catch(e){$('status').textContent='Could not refresh sales: '+e.message;document.getElementById('accessStatus').textContent=e.message;}finally{$('load').disabled=false;}}
$('load').onclick=load;$('period').onchange=()=>{preset();render();};for(const id of ['from','to'])$(id).onchange=()=>{$('period').value='custom';render();};$('more').onclick=()=>{limit+=100;transactions();};load();})();
