'use strict';
window.KBRStaffManager=(()=>{
let profiles=[],busy=false,information=new Map(),adminIds=new Set();
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function tileState(p){if(!p.active)return 'removed';if(adminIds.has(p.user_id)||/(^|[ ._-])zora($|[ ._-])/i.test(p.name+' '+(p.username||'')))return 'admin';return p.duty_day===today()?'on-duty':'off-duty';}
const stateLabel={removed:'Removed',admin:'Admin','on-duty':'On duty','off-duty':'Off duty'};
async function load(){const host=document.getElementById('staffProfiles');try{profiles=await KBRCloud.rows('/rest/v1/kbr_baristas?select=*&order=username.asc.nullslast,name.asc');const owners=await KBRCloud.rows('/rest/v1/kbr_staff?role=eq.owner&select=user_id').catch(()=>[]);adminIds=new Set(owners.map(p=>p.user_id).filter(Boolean));profiles.sort((a,b)=>Number(!a.active)-Number(!b.active)||String(a.username||'').localeCompare(String(b.username||''),'en',{numeric:true,sensitivity:'base'})||a.name.localeCompare(b.name));const extra=await KBRCloud.rows('/rest/v1/kbr_employee_information?select=*').catch(()=>[]);information=new Map(extra.map(x=>[x.barista_id,x]));host.innerHTML=profiles.map(p=>`<button type="button" class="card employee-tile employee-${tileState(p)}" title="${stateLabel[tileState(p)]}" aria-label="${escape(p.name)}, ${escape(p.username||'Username not set')}, ${stateLabel[tileState(p)]}" data-employee="${escape(p.id)}" style="text-align:left;padding:22px;min-height:100px">${!p.active?'<span class="employee-cross" aria-hidden="true">×</span>':''}<strong style="display:block;font-size:1.15em">${escape(p.name)}</strong><span style="display:block;margin-top:8px">${escape(p.username||'Username not set')}</span></button>`).join('');host.querySelectorAll('[data-employee]').forEach(b=>b.onclick=()=>details(b.dataset.employee));}catch(e){host.textContent=e.message;}}
const pencil='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m16 3 5 5-12 12-6 1 1-6Z"/><path d="m14 5 5 5"/></svg>';
function details(id){const p=profiles.find(p=>p.id===id);if(!p)return;const info=information.get(id)||{};KBRSyncUI.screen(p.name,'Employee details',[['Back',()=>KBRSyncUI.close()]]);const box=document.createElement('div');const rows=[['First name',info.first_name||'Not set',null],['Middle name',info.middle_name||'Not set',null],['Last name',info.last_name||'Not set',null],['Birthday',info.birthday||'Not set',null],['Address',info.address||'Not set',null],["Mother’s name",info.mother_name||'Not set',null],["Father’s name",info.father_name||'Not set',null],["Spouse’s name",info.spouse_name||'Not set',null],['Name',p.name,null],['Username',p.username||'Not set',p.username?null:'username'],['Login password',p.user_id?'••••••••':'Not set','password'],['Drink passcode',p.has_passcode?'••••••':'Not set','passcode'],['On duty today',p.duty_day===today()?'Yes':'No','duty'],['Employee ID',info.employee_id||'Not set','employeeId'],['Position',info.position||'Barista','position'],['Phone',info.phone||'Not set','phone'],['Contact email',info.email||'Not set','email'],['Start date',info.started_on||'Not set','startedOn'],['Notes',info.notes||'Not set','notes']];box.innerHTML='<button type="button" data-edit-employee style="margin-bottom:16px">Edit employee</button>'+rows.map(([label,value])=>`<div style="border-bottom:1px solid #ddd;padding:10px 0"><strong>${escape(label)}</strong><span style="display:block;overflow-wrap:anywhere;white-space:pre-wrap">${escape(value)}</span></div>`).join('')+`<p>Status: ${p.active?'Active':'Removed'}</p><p style="font-size:.85em">Saved passwords and passcodes cannot be revealed. Edit to set a new one. Login display names and usernames remain fixed.</p><button type="button" data-staff-action>${p.active?'Remove employee':'Restore employee'}</button>`;document.querySelector('#cloudScreen .cloud-box').append(box);box.querySelector('[data-edit-employee]').onclick=()=>edit(id);box.querySelector('[data-staff-action]').onclick=()=>p.active?remove(id):edit(id);}

function edit(id,field){if(busy)return;const profile=profiles.find(p=>p.id===id);KBRSyncUI.screen(profile?'Edit '+profile.name:'Add barista','Login passwords and drink codes are separate. Saved passwords cannot be displayed. Enter a new password to reset or change it.',[['Back',()=>KBRSyncUI.close()]]);const form=document.createElement('form');form.innerHTML=`<label>Name<input name="name" minlength="2" maxlength="40" required ${profile?'readonly':''} value="${escape(profile?.name||'')}"></label><label>Login username<input name="username" minlength="3" maxlength="30" required ${profile?.username?'readonly':''} value="${escape(profile?.username||profile?.name.toLowerCase().replace(/ /g,'.')||'')}"></label><label>${profile?.user_id?'New password (leave blank to keep)':'Login password'}<input name="password" type="password" minlength="8" autocomplete="new-password" ${profile?.user_id?'':'required'}><button type="button" data-reveal="password" aria-pressed="false">Show password</button><small style="display:block;margin:6px 0 12px">Use at least 8 characters. To reset this login, enter a new password and save.</small></label><label>${profile?.has_passcode?'New drink passcode (leave blank to keep)':'Drink redemption passcode'}<input name="passcode" type="password" inputmode="numeric" minlength="4" maxlength="6" autocomplete="new-password" ${profile?.has_passcode?'':'required'}><button type="button" data-reveal="passcode" aria-pressed="false">Show code</button><small style="display:block;margin:6px 0 12px">Use 4 to 6 digits only, for example 4826. No letters or spaces. This code is used to redeem their Barista Drink.</small></label><label><input name="duty" type="checkbox" ${profile?.duty_day===today()?'checked':''}> On duty today</label><button type="submit">Save barista</button>`;form.querySelector('button[type=submit]').insertAdjacentHTML('beforebegin',KBREmployeeInformation.fields(information.get(id)||{}));document.querySelector('#cloudScreen .cloud-box').append(form);
 for(const button of form.querySelectorAll('[data-reveal]'))button.onclick=()=>{const input=form.elements[button.dataset.reveal],show=input.type==='password';input.type=show?'text':'password';button.textContent=(show?'Hide ':'Show ')+(button.dataset.reveal==='password'?'password':'code');button.setAttribute('aria-pressed',String(show));};
 if(field&&profile?.user_id&&profile?.has_passcode){for(const label of form.querySelectorAll('label')){const input=label.querySelector('input');label.hidden=input?.name!==field;}form.querySelector('button[type=submit]').textContent='Save change';form.elements[field]?.focus();}
 const rules={name:[/^[A-Za-z][A-Za-z -]{1,39}$/, 'Use 2 to 40 characters: letters, spaces, or a hyphen. Start with a letter.'],username:[/^[a-z0-9][a-z0-9._-]{2,29}$/, 'Use 3 to 30 lowercase letters, numbers, dots, underscores, or hyphens. Start with a letter or number.'],passcode:[/^[0-9]{4,6}$/, 'Enter 4 to 6 digits only, for example 4826. No letters or spaces.']};
 for(const [name,[rule,message]] of Object.entries(rules)){const field=form.elements[name];const validate=()=>{field.setCustomValidity(field.value===''&&!field.required?'':rule.test(field.value)?'':message);};field.addEventListener('input',validate);field.addEventListener('invalid',validate);validate();}
 form.onsubmit=async e=>{e.preventDefault();if(busy||!form.reportValidity())return;busy=true;const body={action:'save',id:profile?.id||null,name:form.elements.name.value.trim(),username:form.elements.username.value.trim().toLowerCase(),password:form.elements.password.value,passcode:form.elements.passcode.value,onDuty:form.elements.duty.checked};form.elements.password.value='';form.elements.passcode.value='';try{if(profile)await KBREmployeeInformation.save(profile.id,form);const account=await KBRCloud.request('/functions/v1/kbr-manage-staff',{method:'POST',body:JSON.stringify(body)});if(!profile)await KBREmployeeInformation.save(account.profile.id,form);KBRSyncUI.close();await load();}catch(error){KBRSyncUI.screen('Barista was not saved',error.message+' Some changes may already have saved; reopen the employee to check. Check that the kbr-manage-staff server function is deployed.',[['Back',()=>KBRSyncUI.close()]]);}finally{busy=false;}};
}
function remove(id){if(busy)return;const profile=profiles.find(p=>p.id===id);if(!profile)return;KBRSyncUI.screen('Remove '+profile.name,'This disables their shop access and drink redemption. Existing orders and records are retained.',[['Keep barista',()=>KBRSyncUI.close()],['Remove barista',async()=>{if(busy)return;busy=true;try{await KBRCloud.request('/functions/v1/kbr-manage-staff',{method:'POST',body:JSON.stringify({action:'remove',id})});KBRSyncUI.close();await load();}catch(e){KBRSyncUI.screen('Could not remove barista',e.message,[['Back',()=>KBRSyncUI.close()]]);}finally{busy=false;}}]]);}
return {load,edit,remove,details};})();
